### ISSUE TITLE
object 'icd9_sub_chapters' missing nodes

### ISSUE THREAD

**Issue by sargdavid** [jackwasey/icd.data#1]
Object 'icd9_sub_chapters' missing the following nodes:
280-289:  Diseases Of The Blood And Blood-Forming Organs
740-759:  Congenital Anomalies

**Comment by jackwasey** [comment]
These are chapters, not sub-chapters, I think.
```
icd.data::icd9_chapters$`Diseases Of The Blood And Blood-Forming Organs`
icd.data::icd9_chapters$`Congenital Anomalies`
```
https://icd.codes/icd9cm
